[2022-04-11 20:06:45,154] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.create_weekly_trips_model 2022-02-01T00:00:00+00:00 [None]>
[2022-04-11 20:06:45,171] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.create_weekly_trips_model 2022-02-01T00:00:00+00:00 [None]>
[2022-04-11 20:06:45,171] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:06:45,171] {taskinstance.py:1095} INFO - Starting attempt 19 of 20
[2022-04-11 20:06:45,171] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:06:45,178] {taskinstance.py:1114} INFO - Executing <Task(BigQueryInsertJobOperator): create_weekly_trips_model> on 2022-02-01T00:00:00+00:00
[2022-04-11 20:06:45,183] {standard_task_runner.py:52} INFO - Started process 5736 to run task
[2022-04-11 20:06:45,185] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'create_weekly_trips_model', '2022-02-01T00:00:00+00:00', '--job-id', '345', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpwfsg3sac', '--error-file', '/tmp/tmpql0av8iu']
[2022-04-11 20:06:45,187] {standard_task_runner.py:77} INFO - Job 345: Subtask create_weekly_trips_model
[2022-04-11 20:06:45,221] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.create_weekly_trips_model 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-11 20:06:45,263] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=create_weekly_trips_model
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-11 20:06:45,265] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-11 20:06:45,273] {bigquery.py:1638} INFO - Inserting job ***_divvybikes_elt_pipeline_create_weekly_trips_model_2022_02_01T00_00_00_00_00_efe7f6ab1e6c54b5259bf05e23c2cf81
[2022-04-11 20:06:46,644] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2282, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2245, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1640, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1371, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1361, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 708, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: divvybikes_data_all at [6:8]

(job ID: airflow_divvybikes_elt_pipeline_create_weekly_trips_model_2022_02_01T00_00_00_00_00_efe7f6ab1e6c54b5259bf05e23c2cf81)

                                                    -----Query Job SQL Follows-----                                                     

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE divvybikes_data_all.dm_weekly_trips(
   2:    station STRING, 
   3:    total_weekly_trips INT
   4:)
   5:AS
   6:SELECT divvybikes_data_all.station_map_dim_table.station_name, COUNT (divvybikes_data_all.fact_trips.ride_id) AS total_weekly_trips
   7:FROM divvybikes_data_all.fact_trips
   8:INNER JOIN divvybikes_data_all.station_map_dim_table
   9:    ON fact_trips.start_station_id = station_map_dim_table.station_id
  10:GROUP BY 1
  11:ORDER BY 2;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-11 20:06:46,647] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=create_weekly_trips_model, execution_date=20220201T000000, start_date=20220411T200645, end_date=20220411T200646
[2022-04-11 20:06:46,683] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-11 20:06:46,700] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-11 20:06:46,712] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-11 20:06:46,714] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-11 20:06:46,715] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
