[2022-04-10 16:37:42,213] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.create_weekly_trips_model 2022-02-01T00:00:00+00:00 [None]>
[2022-04-10 16:37:42,234] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.create_weekly_trips_model 2022-02-01T00:00:00+00:00 [None]>
[2022-04-10 16:37:42,234] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-10 16:37:42,234] {taskinstance.py:1095} INFO - Starting attempt 8 of 9
[2022-04-10 16:37:42,234] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-10 16:37:42,243] {taskinstance.py:1114} INFO - Executing <Task(BigQueryInsertJobOperator): create_weekly_trips_model> on 2022-02-01T00:00:00+00:00
[2022-04-10 16:37:42,249] {standard_task_runner.py:52} INFO - Started process 30492 to run task
[2022-04-10 16:37:42,254] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'create_weekly_trips_model', '2022-02-01T00:00:00+00:00', '--job-id', '332', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpkyq3ce4w', '--error-file', '/tmp/tmpx77v20lu']
[2022-04-10 16:37:42,256] {standard_task_runner.py:77} INFO - Job 332: Subtask create_weekly_trips_model
[2022-04-10 16:37:42,294] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.create_weekly_trips_model 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-10 16:37:42,343] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=create_weekly_trips_model
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-10 16:37:42,345] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-10 16:37:42,351] {bigquery.py:1638} INFO - Inserting job ***_divvybikes_elt_pipeline_create_weekly_trips_model_2022_02_01T00_00_00_00_00_7a77b1d653b8c754e0e66e8b61774d82
[2022-04-10 16:37:42,982] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2282, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2245, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1640, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1371, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1361, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 708, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid project ID 'divvybikes_data_all'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.

(job ID: airflow_divvybikes_elt_pipeline_create_weekly_trips_model_2022_02_01T00_00_00_00_00_7a77b1d653b8c754e0e66e8b61774d82)

                                                    -----Query Job SQL Follows-----                                                     

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:SELECT divvybikes_data_all.station_map_dim_table.station_name, COUNT (divvybikes_data_all.fact_trips.ride_id) AS total_weekly_trips
   2:FROM divvybikes_data_all.station_map_dim_table.fact_trips
   3:INNER JOIN station_map_dim_table
   4:    ON divvybikes_data_all.fact_trips.station_id = divvybikes_data_all.station_map_dim_table.station_id
   5:GROUP BY 1
   6:ORDER BY 2
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-10 16:37:42,985] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=create_weekly_trips_model, execution_date=20220201T000000, start_date=20220410T163742, end_date=20220410T163742
[2022-04-10 16:37:43,030] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-10 16:37:43,050] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-10 16:37:43,068] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-10 16:37:43,071] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-10 16:37:43,072] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
