[2022-04-09 20:59:01,272] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.clean_fact_trips_table 2022-02-01T00:00:00+00:00 [None]>
[2022-04-09 20:59:01,291] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.clean_fact_trips_table 2022-02-01T00:00:00+00:00 [None]>
[2022-04-09 20:59:01,291] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-09 20:59:01,291] {taskinstance.py:1095} INFO - Starting attempt 2 of 3
[2022-04-09 20:59:01,291] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-09 20:59:01,298] {taskinstance.py:1114} INFO - Executing <Task(BigQueryExecuteQueryOperator): clean_fact_trips_table> on 2022-02-01T00:00:00+00:00
[2022-04-09 20:59:01,302] {standard_task_runner.py:52} INFO - Started process 5104 to run task
[2022-04-09 20:59:01,305] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'clean_fact_trips_table', '2022-02-01T00:00:00+00:00', '--job-id', '295', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp4iwic474', '--error-file', '/tmp/tmp8mkklko4']
[2022-04-09 20:59:01,307] {standard_task_runner.py:77} INFO - Job 295: Subtask clean_fact_trips_table
[2022-04-09 20:59:01,343] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.clean_fact_trips_table 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-09 20:59:01,368] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1245, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1754, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 997, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 1010, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 1045, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: clean_trips.sql
[2022-04-09 20:59:01,369] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=clean_fact_trips_table, execution_date=20220201T000000, start_date=20220409T205901, end_date=20220409T205901
[2022-04-09 20:59:01,398] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-09 20:59:01,417] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-09 20:59:01,431] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-09 20:59:01,433] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-09 20:59:01,434] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
