[2022-04-09 21:04:13,881] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.clean_fact_trips_table 2022-02-01T00:00:00+00:00 [None]>
[2022-04-09 21:04:13,895] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.clean_fact_trips_table 2022-02-01T00:00:00+00:00 [None]>
[2022-04-09 21:04:13,895] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-09 21:04:13,895] {taskinstance.py:1095} INFO - Starting attempt 5 of 6
[2022-04-09 21:04:13,896] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-09 21:04:13,902] {taskinstance.py:1114} INFO - Executing <Task(BigQueryExecuteQueryOperator): clean_fact_trips_table> on 2022-02-01T00:00:00+00:00
[2022-04-09 21:04:13,906] {standard_task_runner.py:52} INFO - Started process 5666 to run task
[2022-04-09 21:04:13,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'clean_fact_trips_table', '2022-02-01T00:00:00+00:00', '--job-id', '298', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpvnv_ecr9', '--error-file', '/tmp/tmpyyy3k5cx']
[2022-04-09 21:04:13,910] {standard_task_runner.py:77} INFO - Job 298: Subtask clean_fact_trips_table
[2022-04-09 21:04:13,945] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.clean_fact_trips_table 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-09 21:04:13,989] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=clean_fact_trips_table
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-09 21:04:13,990] {bigquery.py:677} INFO - Executing: DELETE FROM external_table
WHERE COALESCE (ended_at, started_at) IS NULL;
[2022-04-09 21:04:13,991] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-09 21:04:13,996] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/google/cloud/hooks/bigquery.py:2194 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-04-09 21:04:14,001] {bigquery.py:1638} INFO - Inserting job ***_1649538254001248_e33d4e488a54b9424dd8507bb60143bc
[2022-04-09 21:04:14,467] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 703, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2329, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1640, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1371, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1361, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 708, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Table "external_table" must be qualified with a dataset (e.g. dataset.table).

(job ID: airflow_1649538254001248_e33d4e488a54b9424dd8507bb60143bc)

          -----Query Job SQL Follows-----          

    |    .    |    .    |    .    |    .    |
   1:DELETE FROM external_table
   2:WHERE COALESCE (ended_at, started_at) IS NULL;
    |    .    |    .    |    .    |    .    |
[2022-04-09 21:04:14,473] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=clean_fact_trips_table, execution_date=20220201T000000, start_date=20220409T210413, end_date=20220409T210414
[2022-04-09 21:04:14,523] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-09 21:04:14,544] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-09 21:04:14,557] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-09 21:04:14,559] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-09 21:04:14,559] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
