[2022-04-09 21:34:06,062] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.create_fact_trips_table 2022-02-01T00:00:00+00:00 [None]>
[2022-04-09 21:34:06,076] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.create_fact_trips_table 2022-02-01T00:00:00+00:00 [None]>
[2022-04-09 21:34:06,077] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-09 21:34:06,077] {taskinstance.py:1095} INFO - Starting attempt 18 of 19
[2022-04-09 21:34:06,077] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-09 21:34:06,084] {taskinstance.py:1114} INFO - Executing <Task(BigQueryInsertJobOperator): create_fact_trips_table> on 2022-02-01T00:00:00+00:00
[2022-04-09 21:34:06,090] {standard_task_runner.py:52} INFO - Started process 8818 to run task
[2022-04-09 21:34:06,093] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'create_fact_trips_table', '2022-02-01T00:00:00+00:00', '--job-id', '319', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmprkm2pknw', '--error-file', '/tmp/tmppq_uuyn2']
[2022-04-09 21:34:06,094] {standard_task_runner.py:77} INFO - Job 319: Subtask create_fact_trips_table
[2022-04-09 21:34:06,133] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.create_fact_trips_table 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-09 21:34:06,174] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=create_fact_trips_table
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-09 21:34:06,177] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-09 21:34:06,185] {bigquery.py:1638} INFO - Inserting job ***_divvybikes_elt_pipeline_create_fact_trips_table_2022_02_01T00_00_00_00_00_2f937b7cfbc444b08b1fb5cfdee2e66d
[2022-04-09 21:34:07,346] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2282, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2245, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1640, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1371, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1361, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 708, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))

(job ID: airflow_divvybikes_elt_pipeline_create_fact_trips_table_2022_02_01T00_00_00_00_00_2f937b7cfbc444b08b1fb5cfdee2e66d)

                -----Query Job SQL Follows-----                 

    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE TABLE IF NOT EXISTS divvybikes_data_all.fact_trips (
   2:    ride_id STRING,
   3:    bike_type STRING,
   4:    ride_start TIMESTAMP,
   5:    ride_end TIMESTAMP, 
   6:    start_station_name STRING,
   7:    start_station_id STRING,
   8:    end_station_name STRING,
   9:    end_station_id STRING,
  10:    member_casual STRING
  11:)
  12:PARTITION BY ride_start
  13:AS
  14:SELECT 
  15:ride_id,
  16:rideable_type AS bike_type,
  17:started_at AS ride_start,
  18:ended_at AS ride_end, 
  19:start_station_name,
  20:start_station_id,
  21:end_station_name,
  22:end_station_id,
  23:member_casual,
  24:
  25:FROM divvybikes_data_all.external_table ;
    |    .    |    .    |    .    |    .    |    .    |
[2022-04-09 21:34:07,349] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=create_fact_trips_table, execution_date=20220201T000000, start_date=20220409T213406, end_date=20220409T213407
[2022-04-09 21:34:07,390] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-09 21:34:07,426] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-09 21:34:07,445] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-09 21:34:07,450] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-09 21:34:07,451] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
