[2022-04-05 13:26:56,113] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_to_gcs_task 2022-02-01T00:00:00+00:00 [up_for_retry]>
[2022-04-05 13:26:56,128] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_to_gcs_task 2022-02-01T00:00:00+00:00 [up_for_retry]>
[2022-04-05 13:26:56,128] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 13:26:56,129] {taskinstance.py:1095} INFO - Starting attempt 3 of 3
[2022-04-05 13:26:56,129] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 13:26:56,144] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): upload_to_gcs_task> on 2022-02-01T00:00:00+00:00
[2022-04-05 13:26:56,157] {standard_task_runner.py:52} INFO - Started process 3047 to run task
[2022-04-05 13:26:56,161] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'upload_to_gcs_task', '2022-02-01T00:00:00+00:00', '--job-id', '234', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpz0te1u04', '--error-file', '/tmp/tmpt1vrv795']
[2022-04-05 13:26:56,172] {standard_task_runner.py:77} INFO - Job 234: Subtask upload_to_gcs_task
[2022-04-05 13:26:56,215] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.upload_to_gcs_task 2022-02-01T00:00:00+00:00 [running]> on host cb4014871cd0
[2022-04-05 13:26:56,279] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=upload_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-05 13:26:56,281] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_load.py", line 73, in upload_to_gcs
    client = storage.Client()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/client.py", line 128, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 318, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 266, in __init__
    project = self._determine_default(project)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 285, in _determine_default
    return _determine_default_project(project)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 459, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS]
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File /home/hartyquinn/github/de-bike-tripdata/gcloud_key/sturdy-dogfish-344515-f76fb8890f3e.json was not found.
[2022-04-05 13:26:56,292] {taskinstance.py:1512} INFO - Marking task as FAILED. dag_id=divvybikes_elt_pipeline, task_id=upload_to_gcs_task, execution_date=20220201T000000, start_date=20220405T132656, end_date=20220405T132656
[2022-04-05 13:26:56,376] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-05 13:26:56,410] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
