[2022-04-08 02:08:26,664] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_station_map_upload.upload_to_gcs_task 2021-01-01T00:00:00+00:00 [queued]>
[2022-04-08 02:08:26,682] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_station_map_upload.upload_to_gcs_task 2021-01-01T00:00:00+00:00 [queued]>
[2022-04-08 02:08:26,682] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-08 02:08:26,682] {taskinstance.py:1095} INFO - Starting attempt 7 of 7
[2022-04-08 02:08:26,682] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-08 02:08:26,691] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): upload_to_gcs_task> on 2021-01-01T00:00:00+00:00
[2022-04-08 02:08:26,695] {standard_task_runner.py:52} INFO - Started process 16727 to run task
[2022-04-08 02:08:26,698] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_station_map_upload', 'upload_to_gcs_task', '2021-01-01T00:00:00+00:00', '--job-id', '270', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stations_to_gcs.py', '--cfg-path', '/tmp/tmp5leu72_x', '--error-file', '/tmp/tmp8zw58iay']
[2022-04-08 02:08:26,700] {standard_task_runner.py:77} INFO - Job 270: Subtask upload_to_gcs_task
[2022-04-08 02:08:26,736] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_station_map_upload.upload_to_gcs_task 2021-01-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-08 02:08:26,784] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_station_map_upload
AIRFLOW_CTX_TASK_ID=upload_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-04-08 02:08:26,795] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stations_to_gcs.py", line 50, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2719, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/datasets/Divvy_Bicycle_Stations_-_All_-_Map.csv'
[2022-04-08 02:08:26,797] {taskinstance.py:1512} INFO - Marking task as FAILED. dag_id=divvybikes_station_map_upload, task_id=upload_to_gcs_task, execution_date=20210101T000000, start_date=20220408T020826, end_date=20220408T020826
[2022-04-08 02:08:26,831] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-08 02:08:26,855] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
