[2022-04-01 20:28:41,512] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.extract_csv 2020-04-01T00:00:00+00:00 [queued]>
[2022-04-01 20:28:41,523] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.extract_csv 2020-04-01T00:00:00+00:00 [queued]>
[2022-04-01 20:28:41,523] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:28:41,524] {taskinstance.py:1095} INFO - Starting attempt 2 of 3
[2022-04-01 20:28:41,524] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:28:41,530] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): extract_csv> on 2020-04-01T00:00:00+00:00
[2022-04-01 20:28:41,534] {standard_task_runner.py:52} INFO - Started process 31891 to run task
[2022-04-01 20:28:41,536] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'extract_csv', '2020-04-01T00:00:00+00:00', '--job-id', '89', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp90j8lev5', '--error-file', '/tmp/tmpsos_lx0f']
[2022-04-01 20:28:41,537] {standard_task_runner.py:77} INFO - Job 89: Subtask extract_csv
[2022-04-01 20:28:41,564] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.extract_csv 2020-04-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 20:28:41,600] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=extract_csv
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2020-04-01T00:00:00+00:00
[2022-04-01 20:28:41,601] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_load.py", line 85, in extract_csv_from_zip
    zip_file = zipfile.ZipFile(zipped_file)
  File "/usr/local/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/datasets///opt/airflow/dags/datasets/202004-divvy-tripdata.zip'
[2022-04-01 20:28:41,603] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=extract_csv, execution_date=20200401T000000, start_date=20220401T202841, end_date=20220401T202841
[2022-04-01 20:28:41,629] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-01 20:28:41,650] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
