[2022-04-07 00:50:14,362] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.gcs_to_external_table_Task 2022-02-01T00:00:00+00:00 [None]>
[2022-04-07 00:50:14,371] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.gcs_to_external_table_Task 2022-02-01T00:00:00+00:00 [None]>
[2022-04-07 00:50:14,371] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:50:14,371] {taskinstance.py:1095} INFO - Starting attempt 4 of 5
[2022-04-07 00:50:14,371] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:50:14,381] {taskinstance.py:1114} INFO - Executing <Task(BigQueryCreateExternalTableOperator): gcs_to_external_table_Task> on 2022-02-01T00:00:00+00:00
[2022-04-07 00:50:14,386] {standard_task_runner.py:52} INFO - Started process 782 to run task
[2022-04-07 00:50:14,388] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'gcs_to_external_table_Task', '2022-02-01T00:00:00+00:00', '--job-id', '249', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpbxw_o2yh', '--error-file', '/tmp/tmpfnyjvz7w']
[2022-04-07 00:50:14,390] {standard_task_runner.py:77} INFO - Job 249: Subtask gcs_to_external_table_Task
[2022-04-07 00:50:14,423] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.gcs_to_external_table_Task 2022-02-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-07 00:50:14,459] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=gcs_to_external_table_Task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-02-01T00:00:00+00:00
[2022-04-07 00:50:14,461] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 00:50:14,470] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/google/cloud/hooks/bigquery.py:637 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.create_empty_table` method withpass passing the `table_resource` object. This gives more flexibility than this method.
[2022-04-07 00:50:14,470] {bigquery.py:700} INFO - Creating external table: sturdy-dogfish-344515.divvybikes_data_all.external_table
[2022-04-07 00:50:15,021] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1215, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 702, in create_external_table
    table_resource=table.to_api_repr(), project_id=project_id, location=location, exists_ok=True
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 729, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 747, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/sturdy-dogfish-344515/datasets/divvybikes_data_all/tables?prettyPrint=false: Error while reading table: external_table, error message: Failed to expand table external_table with file pattern gs://divvybikes_data_lake_sturdy-dogfish-344515/gs://divvybikes_data_lake_sturdy-dogfish-344515/raw/*: matched no files.
[2022-04-07 00:50:15,024] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=gcs_to_external_table_Task, execution_date=20220201T000000, start_date=20220407T005014, end_date=20220407T005015
[2022-04-07 00:50:15,043] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-07 00:50:15,059] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 00:50:15,071] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.bq_staging_table_task 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-07 00:50:15,073] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.create_s3_connection 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
[2022-04-07 00:50:15,073] {dagrun.py:486} WARNING - Failed to get task '<TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-02-01 00:00:00+00:00 [removed]>' for dag 'divvybikes_elt_pipeline'. Marking it as removed.
