[2022-04-11 20:23:55,056] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.extract_csv 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-11 20:23:55,072] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.extract_csv 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-11 20:23:55,072] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:23:55,072] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-04-11 20:23:55,073] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:23:55,083] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): extract_csv> on 2022-03-01T00:00:00+00:00
[2022-04-11 20:23:55,087] {standard_task_runner.py:52} INFO - Started process 7547 to run task
[2022-04-11 20:23:55,090] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'extract_csv', '2022-03-01T00:00:00+00:00', '--job-id', '353', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpr6wn1v_h', '--error-file', '/tmp/tmpx21jbmi_']
[2022-04-11 20:23:55,092] {standard_task_runner.py:77} INFO - Job 353: Subtask extract_csv
[2022-04-11 20:23:55,127] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.extract_csv 2022-03-01T00:00:00+00:00 [running]> on host afa4c4c5de3b
[2022-04-11 20:23:55,173] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=extract_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-01T00:00:00+00:00
[2022-04-11 20:23:55,174] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_load.py", line 43, in extract_csv_from_zip
    zip_file = zipfile.ZipFile(zipped_file)
NameError: name 'zipfile' is not defined
[2022-04-11 20:23:55,175] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=extract_csv, execution_date=20220301T000000, start_date=20220411T202355, end_date=20220411T202355
[2022-04-11 20:23:55,223] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-11 20:23:55,252] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
