[2022-03-28 23:36:43,688] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: extract_load_to_s3.stream_files_to_memory 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-28 23:36:43,697] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: extract_load_to_s3.stream_files_to_memory 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-28 23:36:43,697] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 23:36:43,697] {taskinstance.py:1095} INFO - Starting attempt 5 of 6
[2022-03-28 23:36:43,698] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 23:36:43,707] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): stream_files_to_memory> on 2022-03-20T00:00:00+00:00
[2022-03-28 23:36:43,712] {standard_task_runner.py:52} INFO - Started process 8235 to run task
[2022-03-28 23:36:43,714] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'extract_load_to_s3', 'stream_files_to_memory', '2022-03-20T00:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpa60emos6', '--error-file', '/tmp/tmpbn1gp3w_']
[2022-03-28 23:36:43,715] {standard_task_runner.py:77} INFO - Job 7: Subtask stream_files_to_memory
[2022-03-28 23:36:43,744] {logging_mixin.py:109} INFO - Running <TaskInstance: extract_load_to_s3.stream_files_to_memory 2022-03-20T00:00:00+00:00 [running]> on host 8fbdc4bc64eb
[2022-03-28 23:36:43,779] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_load_to_s3
AIRFLOW_CTX_TASK_ID=stream_files_to_memory
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-20T00:00:00+00:00
[2022-03-28 23:36:43,781] {logging_mixin.py:109} INFO - https://divvy-tripdata.s3.amazonaws.com/202004-divvy-tripdata.zip
[2022-03-28 23:36:43,781] {logging_mixin.py:109} INFO - Problem downloading Zip File, check URL template
[2022-03-28 23:36:43,781] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_load.py", line 63, in download_files_in_parallel
    if response.status_code == 200:
UnboundLocalError: local variable 'response' referenced before assignment
[2022-03-28 23:36:43,782] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_load_to_s3, task_id=stream_files_to_memory, execution_date=20220320T000000, start_date=20220328T233643, end_date=20220328T233643
[2022-03-28 23:36:43,808] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-03-28 23:36:43,825] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
