[2022-03-28 23:56:14,165] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: extract_load_to_s3.convert_file_to_parquet 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-28 23:56:14,183] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: extract_load_to_s3.convert_file_to_parquet 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-28 23:56:14,183] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 23:56:14,184] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-03-28 23:56:14,184] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 23:56:14,194] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): convert_file_to_parquet> on 2022-03-20T00:00:00+00:00
[2022-03-28 23:56:14,198] {standard_task_runner.py:52} INFO - Started process 793 to run task
[2022-03-28 23:56:14,201] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'extract_load_to_s3', 'convert_file_to_parquet', '2022-03-20T00:00:00+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpt3jia3da', '--error-file', '/tmp/tmp1amthkpm']
[2022-03-28 23:56:14,203] {standard_task_runner.py:77} INFO - Job 14: Subtask convert_file_to_parquet
[2022-03-28 23:56:14,236] {logging_mixin.py:109} INFO - Running <TaskInstance: extract_load_to_s3.convert_file_to_parquet 2022-03-20T00:00:00+00:00 [running]> on host 06cd4100c9db
[2022-03-28 23:56:14,285] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_load_to_s3
AIRFLOW_CTX_TASK_ID=convert_file_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-20T00:00:00+00:00
[2022-03-28 23:56:14,288] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: convert_to_parquet() missing 2 required positional arguments: 'file_name' and 'file_object'
[2022-03-28 23:56:14,290] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_load_to_s3, task_id=convert_file_to_parquet, execution_date=20220320T000000, start_date=20220328T235614, end_date=20220328T235614
[2022-03-28 23:56:14,335] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-03-28 23:56:14,358] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
